// Synced from powermath-trainer @ 85699c4 (tooling/content-neutral).
// Diverged here for Y6: extra entries (coordinates, brackets, HCF vocabulary,
// Y6 story nouns) and the -ied rule. The Y5 app is frozen at v16, so there is
// no live upstream to sync these back to.
// English → German word glosses for the lesson text.
//
// The app teaches maths in English to a child whose English is still weak.
// German is deliberately available at WORD level only: a whole-lesson
// translation lets him skip the English entirely, a single word does not.
//
// This list is the offline backbone. It covers the maths and instruction
// vocabulary that actually occurs in the content modules (candidate list from
// `python3 tools/vocab.py`), so the common case needs no network and no API
// key. Anything not in here goes to the tutor for a one-word gloss in context.
//
// Style rules for an entry:
// - the MATHS sense first, everyday sense after it in brackets
//   ('left' is "übrig" in this app far more often than "links")
// - short enough to read in a popover: one line, no sentences
// - the word alone, not a definition — he needs the meaning, not a lesson

export const GLOSSARY = {
  // ---- number and place value
  number: 'die Zahl',
  digit: 'die Ziffer (eine einzelne Zahl von 0 bis 9)',
  place: 'die Stelle (z. B. Zehnerstelle)',
  value: 'der Wert',
  ones: 'die Einer',
  tens: 'die Zehner',
  hundreds: 'die Hunderter',
  thousands: 'die Tausender',
  'ten-thousands': 'die Zehntausender',
  hundred: 'hundert',
  thousand: 'tausend',
  million: 'die Million',
  zero: 'die Null',
  whole: 'ganz, das Ganze',
  negative: 'negativ (kleiner als null)',
  positive: 'positiv (größer als null)',
  decimal: 'die Dezimalzahl (mit Komma)',
  point: 'der Punkt — im Englischen das Komma (3.5 = 3,5)',
  comma: 'das Komma — im Englischen der Tausenderpunkt (1,000 = 1000)',
  tenths: 'die Zehntel',
  hundredths: 'die Hundertstel',
  thousandths: 'die Tausendstel',
  round: 'runden (auch: rund)',
  nearest: 'am nächsten, nächstgelegen',
  estimate: 'schätzen, die Schätzung',
  count: 'zählen',
  order: 'ordnen, die Reihenfolge',
  compare: 'vergleichen',
  bigger: 'größer',
  smaller: 'kleiner',
  biggest: 'am größten',
  smallest: 'am kleinsten',
  greater: 'größer',
  less: 'weniger',
  more: 'mehr',
  than: 'als (beim Vergleichen)',
  between: 'zwischen',
  equal: 'gleich',
  equals: 'ist gleich (=)',
  exactly: 'genau',
  exact: 'genau',
  column: 'die Spalte (untereinander rechnen)',
  row: 'die Reihe, die Zeile',
  carry: 'der Übertrag, übertragen',
  exchange: 'tauschen, bündeln (exchange)',
  sequence: 'die Zahlenfolge',
  pattern: 'das Muster',
  rule: 'die Regel',

  // ---- the four operations
  add: 'addieren, dazuzählen',
  addition: 'die Addition (plus)',
  plus: 'plus (+)',
  subtract: 'subtrahieren, abziehen',
  subtraction: 'die Subtraktion (minus)',
  minus: 'minus (−)',
  multiply: 'multiplizieren, malnehmen',
  multiplication: 'die Multiplikation (mal)',
  times: 'mal (×)',
  divide: 'teilen, dividieren',
  division: 'die Division (geteilt durch)',
  remainder: 'der Rest',
  leftover: 'der Rest, das Übriggebliebene',
  left: 'übrig (auch: links)',
  share: 'aufteilen, verteilen',
  inverse: 'die Umkehrung (Gegenrechnung)',
  total: 'die Summe, insgesamt',
  altogether: 'insgesamt',
  sum: 'die Summe, die Rechenaufgabe',
  difference: 'die Differenz, der Unterschied',
  product: 'das Produkt (Ergebnis beim Malnehmen)',
  factor: 'der Faktor, der Teiler',
  multiple: 'das Vielfache',
  prime: 'die Primzahl',
  square: 'das Quadrat; die Quadratzahl',
  cube: 'der Würfel; die Kubikzahl',
  method: 'der Rechenweg, die Methode',
  answer: 'die Antwort, das Ergebnis',
  calculate: 'rechnen, ausrechnen',
  calculation: 'die Rechnung',
  operation: 'die Rechenart (+ − × ÷)',
  fact: 'die Rechenaufgabe, die Tatsache',

  // ---- fractions, decimals, percentages
  fraction: 'der Bruch',
  numerator: 'der Zähler (oben)',
  denominator: 'der Nenner (unten)',
  improper: 'unecht (Zähler größer als Nenner)',
  mixed: 'gemischt (ganze Zahl + Bruch)',
  equivalent: 'gleichwertig (gleich groß)',
  simplify: 'kürzen, vereinfachen',
  half: 'die Hälfte, halb',
  quarter: 'das Viertel',
  third: 'das Drittel; der/die/das Dritte',
  fifth: 'das Fünftel',
  piece: 'das Stück',
  part: 'der Teil',
  split: 'aufteilen, zerlegen',
  cut: 'schneiden, zerschneiden',
  percentage: 'der Prozentsatz',
  percent: 'Prozent (%)',
  per: 'pro, je',
  ratio: 'das Verhältnis',
  proportion: 'der Anteil, das Verhältnis',

  // ---- measurement
  measure: 'messen, das Maß',
  unit: 'die Einheit',
  metric: 'metrisch (cm, m, kg, l)',
  imperial: 'britische Maße (inch, pound, pint)',
  convert: 'umrechnen, umwandeln',
  length: 'die Länge',
  width: 'die Breite',
  wide: 'breit',
  long: 'lang',
  height: 'die Höhe',
  tall: 'hoch, groß',
  deep: 'tief',
  perimeter: 'der Umfang (einmal außen herum)',
  area: 'der Flächeninhalt',
  volume: 'das Volumen (der Rauminhalt)',
  capacity: 'das Fassungsvermögen',
  holds: 'fasst (passt hinein)',
  weight: 'das Gewicht',
  mass: 'die Masse (das Gewicht)',
  size: 'die Größe',
  scale: 'die Skala; der Maßstab',
  distance: 'die Entfernung, die Strecke',
  temperature: 'die Temperatur',
  metres: 'die Meter',
  centimetres: 'die Zentimeter',
  millimetres: 'die Millimeter',
  kilometres: 'die Kilometer',
  litres: 'die Liter',
  grams: 'die Gramm',
  kilograms: 'die Kilogramm',
  inches: 'die Zoll (1 inch ≈ 2,5 cm)',
  feet: 'die Fuß (1 foot ≈ 30 cm); die Füße',
  pint: 'die Pinte (etwa 0,57 Liter)',
  cm: 'Zentimeter',
  mm: 'Millimeter',
  km: 'Kilometer',
  ml: 'Milliliter',
  kg: 'Kilogramm',
  degrees: 'die Grad (°)',
  minute: 'die Minute',
  second: 'die Sekunde; der/die/das Zweite',
  hour: 'die Stunde',
  day: 'der Tag',
  week: 'die Woche',
  month: 'der Monat',
  year: 'das Jahr',
  time: 'die Zeit; das Mal',
  clock: 'die Uhr',

  // ---- geometry, position and direction
  shape: 'die Form, die Figur',
  angle: 'der Winkel',
  acute: 'spitz (Winkel unter 90°)',
  obtuse: 'stumpf (Winkel über 90°)',
  reflex: 'überstumpf (Winkel über 180°)',
  straight: 'gerade',
  side: 'die Seite',
  corner: 'die Ecke',
  vertex: 'der Eckpunkt',
  vertices: 'die Eckpunkte',
  face: 'die Fläche (eines Körpers); das Gesicht',
  edge: 'die Kante',
  parallel: 'parallel (gleicher Abstand)',
  perpendicular: 'senkrecht (im rechten Winkel)',
  regular: 'regelmäßig (alle Seiten gleich)',
  polygon: 'das Vieleck',
  rectangle: 'das Rechteck',
  triangle: 'das Dreieck',
  circle: 'der Kreis',
  grid: 'das Gitter, das Karo',
  line: 'die Linie',
  reflection: 'die Spiegelung',
  mirror: 'der Spiegel, spiegeln',
  translation: 'die Verschiebung',
  rotate: 'drehen',
  turn: 'die Drehung, drehen; an der Reihe sein',
  coordinate: 'die Koordinate',
  axis: 'die Achse',
  horizontal: 'waagerecht',
  vertical: 'senkrecht',
  position: 'die Position, der Ort',
  direction: 'die Richtung',
  clockwise: 'im Uhrzeigersinn',

  // ---- data and diagrams
  table: 'die Tabelle (auch: der Tisch)',
  chart: 'das Diagramm',
  graph: 'der Graph, das Schaubild',
  bar: 'der Balken',
  data: 'die Daten',
  average: 'der Durchschnitt',
  survey: 'die Umfrage',
  model: 'das Modell',
  diagram: 'das Schaubild, die Zeichnung',
  label: 'die Beschriftung, beschriften',

  // ---- instructions and lesson verbs
  find: 'finden, herausfinden',
  write: 'schreiben',
  read: 'lesen',
  say: 'sagen',
  tell: 'sagen, erzählen',
  show: 'zeigen',
  draw: 'zeichnen',
  check: 'prüfen, nachprüfen',
  choose: 'auswählen',
  pick: 'aussuchen',
  match: 'zuordnen, passen',
  sort: 'sortieren',
  use: 'benutzen, verwenden',
  make: 'machen, bilden',
  give: 'geben',
  need: 'brauchen',
  keep: 'behalten, weitermachen',
  start: 'anfangen',
  stop: 'aufhören',
  finish: 'fertig werden',
  complete: 'vollständig; fertig machen',
  try: 'versuchen',
  think: 'denken, nachdenken',
  know: 'wissen, kennen',
  remember: 'sich erinnern, merken',
  imagine: 'sich vorstellen',
  look: 'schauen',
  spot: 'entdecken',
  fit: 'passen, hineinpassen',
  put: 'setzen, legen',
  take: 'nehmen',
  move: 'bewegen, verschieben',
  stay: 'bleiben',
  jump: 'springen',
  land: 'landen',
  ask: 'fragen',
  mean: 'bedeuten; gemein',
  means: 'bedeutet',
  become: 'werden',
  change: 'ändern, wechseln; das Wechselgeld',
  decide: 'entscheiden',
  swap: 'tauschen',
  shift: 'verschieben, rücken',
  miss: 'verpassen, übersehen',
  missing: 'fehlend',
  leave: 'lassen, übrig lassen',
  meet: 'treffen, sich begegnen',
  work: 'arbeiten, funktionieren; die Rechnung',
  solve: 'lösen',
  step: 'der Schritt',
  explain: 'erklären',
  practise: 'üben',

  // ---- words that trip a German reader up
  each: 'jede/jeder/jedes',
  every: 'jede/jeder/jedes',
  both: 'beide',
  only: 'nur',
  other: 'andere',
  same: 'gleich, dasselbe',
  different: 'verschieden, anders',
  again: 'noch einmal, wieder',
  still: 'immer noch',
  first: 'zuerst, erste',
  next: 'als Nächstes, nächste',
  then: 'dann',
  after: 'nach, danach',
  before: 'vor, davor',
  past: 'nach (bei Uhrzeit); vorbei',
  back: 'zurück',
  away: 'weg',
  around: 'herum, ungefähr',
  together: 'zusammen',
  about: 'ungefähr; über',
  over: 'über; bei Brüchen: geteilt durch',
  under: 'unter',
  through: 'durch',
  along: 'entlang',
  across: 'quer über, hinüber',
  far: 'weit',
  wrong: 'falsch',
  right: 'richtig; rechts; rechter Winkel',
  true: 'wahr, stimmt',
  false: 'falsch, stimmt nicht',
  always: 'immer',
  never: 'nie',
  once: 'einmal',
  twice: 'zweimal',
  enough: 'genug',
  extra: 'zusätzlich',
  amount: 'die Menge',
  worth: 'wert',
  own: 'eigen',
  itself: 'sich selbst',
  way: 'der Weg, die Art und Weise',
  trick: 'der Trick',
  story: 'die Geschichte (Textaufgabe)',
  word: 'das Wort',
  question: 'die Frage, die Aufgabe',
  easier: 'einfacher',
  easy: 'einfach',
  hard: 'schwer, schwierig',
  quick: 'schnell',
  real: 'echt, wirklich',
  common: 'gemeinsam, häufig',
  little: 'klein, wenig',
  big: 'groß',
  small: 'klein',
  short: 'kurz',
  full: 'voll',
  empty: 'leer',
  new: 'neu',
  top: 'oben, das Obere',
  bottom: 'unten, das Untere',
  middle: 'die Mitte',
  inside: 'innen, hinein',
  outside: 'außen',
  below: 'unter, darunter',
  above: 'über, darüber',
  backwards: 'rückwärts',
  forwards: 'vorwärts',
  down: 'runter, hinunter',
  up: 'hoch, hinauf',

  // ---- the small words that carry the instruction
  how: 'wie',
  many: 'viele ("how many" = wie viele)',
  much: 'viel ("how much" = wie viel)',
  when: 'wann, wenn',
  where: 'wo',
  why: 'warum',
  which: 'welche/welcher/welches',
  what: 'was',
  out: 'heraus, aus',
  into: 'hinein, in',
  like: 'wie; mögen',
  just: 'einfach, gerade eben',
  all: 'alle, alles',
  some: 'einige, etwas',
  any: 'irgendein, überhaupt',
  most: 'die meisten, am meisten',
  least: 'am wenigsten ("at least" = mindestens)',
  even: 'gerade (Zahl); sogar',
  odd: 'ungerade (Zahl); seltsam',
  nothing: 'nichts',
  something: 'etwas',
  without: 'ohne',
  roughly: 'ungefähr',
  further: 'weiter',
  except: 'außer',
  because: 'weil',
  too: 'zu (zu groß); auch',
  there: 'dort, da',
  now: 'jetzt',
  yes: 'ja',
  no: 'nein, kein',
  must: 'müssen',
  should: 'sollen',
  would: 'würde',
  cannot: 'kann nicht',
  get: 'bekommen, werden',
  go: 'gehen',
  end: 'das Ende',
  last: 'letzte; dauern',
  good: 'gut',
  done: 'fertig, erledigt',
  known: 'bekannt',
  mental: 'im Kopf ("mental method" = Kopfrechnen)',
  friendly: 'freundlich ("friendly number" = eine bequeme Zahl)',
  group: 'die Gruppe, gruppieren',
  example: 'das Beispiel',
  problem: 'die Aufgabe, das Problem',
  picture: 'das Bild',
  dot: 'der Punkt',
  floor: 'der Boden; das Stockwerk',
  pass: 'vorbeigehen, weitergeben',
  book: 'das Buch',
  job: 'die Aufgabe, der Job',
  club: 'der Verein, der Klub',
  walk: 'laufen, zu Fuß gehen',
  sit: 'sitzen',
  come: 'kommen',
  their: 'ihr, ihre',

  // ---- grammar words. He knows most of them — but "tap any word" has to be
  // true, and a popover saying "kenne ich nicht" on 'the' would read as broken.
  the: 'der, die, das',
  a: 'ein, eine',
  an: 'ein, eine',
  is: 'ist',
  are: 'sind',
  was: 'war',
  were: 'waren',
  be: 'sein',
  been: 'gewesen',
  has: 'hat',
  have: 'haben',
  do: 'tun, machen',
  does: 'tut, macht',
  did: 'tat, machte',
  can: 'können',
  will: 'werden (Zukunft)',
  and: 'und',
  or: 'oder',
  but: 'aber',
  if: 'wenn, falls',
  though: 'obwohl',
  however: 'aber, jedoch',
  so: 'also, so',
  to: 'zu, nach',
  of: 'von (Zugehörigkeit)',
  in: 'in',
  on: 'auf',
  at: 'an, bei',
  for: 'für',
  from: 'von, aus',
  with: 'mit',
  by: 'durch, mit; von',
  as: 'als, wie',
  not: 'nicht',
  it: 'es',
  its: 'sein, ihr (Besitz)',
  this: 'dies, diese/dieser/dieses',
  that: 'das, jene/jener/jenes',
  these: 'diese (Mehrzahl)',
  those: 'jene (Mehrzahl)',
  they: 'sie (Mehrzahl)',
  them: 'sie, ihnen',
  you: 'du, ihr',
  your: 'dein, euer',
  we: 'wir',
  us: 'uns',
  he: 'er',
  she: 'sie',
  i: 'ich; die römische Zahl 1',
  who: 'wer',
  often: 'oft',
  sometimes: 'manchmal',
  separately: 'einzeln, getrennt',
  forever: 'für immer, endlos',
  said: 'sagte',
  wrote: 'schrieb',
  happen: 'passieren, geschehen',
  depend: 'abhängen',
  join: 'verbinden',
  let: 'lassen',
  live: 'leben; wohnen',
  rise: 'steigen',
  beat: 'schlagen; schlagen (besser sein)',
  name: 'der Name, nennen',
  helpful: 'hilfreich',
  neat: 'ordentlich, sauber',

  // ---- number words
  one: 'eins, ein',
  two: 'zwei',
  three: 'drei',
  four: 'vier',
  five: 'fünf',
  six: 'sechs',
  seven: 'sieben',
  eight: 'acht',
  nine: 'neun',
  twelve: 'zwölf',
  tenth: 'das Zehntel; der/die/das Zehnte',
  hundredth: 'das Hundertstel',
  thousandth: 'das Tausendstel',
  'hundred-thousands': 'die Hunderttausender',

  // ---- abbreviations and Roman numerals (they read as words on screen)
  m: 'Meter',
  g: 'Gramm',
  l: 'Liter; die römische Zahl 50',
  p: 'Pence (britische Cent)',
  v: 'die römische Zahl 5',
  x: 'die römische Zahl 10; mal (×)',
  c: 'die römische Zahl 100',
  d: 'die römische Zahl 500',
  iv: 'die römische Zahl 4',
  ix: 'die römische Zahl 9',
  xc: 'die römische Zahl 90',
  roman: 'römisch',
  numeral: 'das Zahlzeichen',
  cent: 'der Cent (100stel)',

  // ---- the remaining lesson words
  protractor: 'das Geodreieck, der Winkelmesser',
  cuboid: 'der Quader',
  octagon: 'das Achteck',
  pentagon: 'das Fünfeck',
  hexagon: 'das Sechseck',
  layer: 'die Schicht, die Lage',
  opposite: 'gegenüber, das Gegenteil',
  shortcut: 'die Abkürzung',
  flat: 'flach',
  space: 'der Platz, der Raum',
  close: 'nah; schließen',
  boundary: 'die Grenze',
  disguise: 'die Verkleidung ("in disguise" = verkleidet)',
  family: 'die Familie',
  golden: 'golden',
  arm: 'der Arm (Schenkel eines Winkels)',
  mile: 'die Meile (etwa 1,6 km)',
  bus: 'der Bus',
  letter: 'der Buchstabe; der Brief',
  front: 'vorne, die Vorderseite',
  thermometer: 'das Thermometer',
  basement: 'das Untergeschoss, der Keller',
  lift: 'der Aufzug; heben',
  cold: 'kalt',
  ten: 'zehn',
  slide: 'rutschen, gleiten (die Ziffer rutscht eine Stelle)',
  litre: 'der Liter',
  'l-shape': 'die L-Form (zusammengesetztes Rechteck)',
  house: 'das Haus',
  impossible: 'unmöglich',
  chain: 'die Kette',
  ripple: 'die Welle (der Übertrag läuft weiter)',
  clever: 'clever, schlau',
  strategy: 'die Strategie, der Trick',
  fast: 'schnell',
  rough: 'grob, ungefähr',
  expect: 'erwarten',
  undo: 'rückgängig machen',
  build: 'bauen',
  rose: 'stieg (Vergangenheit von rise)',

  // ---- Y6 additions: coordinates, brackets, factors and the Y6 lesson voice
  bracket: 'die Klammer',
  'x-axis': 'die x-Achse (waagerecht)',
  'y-axis': 'die y-Achse (senkrecht)',
  'x-coordinate': 'die x-Koordinate (wie weit nach rechts)',
  'y-coordinate': 'die y-Koordinate (wie weit nach oben)',
  quadrant: 'der Quadrant (ein Viertel des Gitters)',
  origin: 'der Ursprung (0, 0)',
  flip: 'umklappen, spiegeln',
  reflect: 'spiegeln',
  sign: 'das Vorzeichen (+ oder −); das Schild',
  cross: 'kreuzen, überqueren; das Kreuz',
  written: 'geschrieben, schriftlich',
  form: 'die Form; bilden',
  grow: 'wachsen',
  near: 'nahe, in der Nähe',
  also: 'auch',
  carefully: 'sorgfältig, vorsichtig',
  reverse: 'umgekehrt, rückwärts',
  borrow: 'leihen (beim Abziehen: eintauschen)',
  divisor: 'der Teiler (die Zahl, durch die geteilt wird)',
  multiplier: 'der Multiplikator (die Zahl, mit der malgenommen wird)',
  neighbour: 'der Nachbar',
  hop: 'der Hüpfer, hüpfen',
  run: 'laufen; die Reihe (a run of numbers)',
  head: 'der Kopf ("in your head" = im Kopf)',
  sense: 'der Sinn ("makes sense" = ergibt Sinn)',
  list: 'die Liste, auflisten',
  best: 'am besten, beste',
  friend: 'der Freund, die Freundin',
  jot: 'schnell notieren',
  bit: 'das Stückchen, ein bisschen',
  'left-over': 'übrig geblieben',
  high: 'hoch',
  'ten-thousand': 'zehntausend',
  'hundred-thousand': 'hunderttausend',
  went: 'ging (Vergangenheit von go)',
  nowhere: 'nirgendwo',
  yourself: 'du selbst, dich selbst',
  gym: 'die Turnhalle, der Sport',
  station: 'der Bahnhof, die Haltestelle',
  corridor: 'der Flur, der Gang',
  stairs: 'die Treppe',
  notebook: 'das Heft, das Notizbuch',
  fee: 'die Gebühr',
  delivery: 'die Lieferung',
  recipe: 'das Rezept',
  route: 'die Route, der Weg',
  ribbon: 'das Band',
  concert: 'das Konzert',
  coach: 'der Reisebus; der Trainer',
  fortnight: 'vierzehn Tage (zwei Wochen)',
  dawn: 'die Morgendämmerung, früh am Morgen',
  overnight: 'über Nacht',
  surface: 'die Oberfläche',
  charity: 'die Spendenaktion, die Wohltätigkeit',
  dozen: 'das Dutzend (12 Stück)',
  badge: 'das Abzeichen',
  lorry: 'der Lastwagen',
  crate: 'die Kiste',
  bruised: 'angestoßen (mit Druckstelle)',
  museum: 'das Museum',
  passenger: 'der Fahrgast',
  theatre: 'das Theater',
  bakery: 'die Bäckerei',
  roll: 'das Brötchen; rollen',
  farm: 'der Bauernhof',
  egg: 'das Ei',
  jar: 'das Glas (Gefäß)',

  // ---- things that turn up in word problems
  apple: 'der Apfel',
  pizza: 'die Pizza',
  cake: 'der Kuchen',
  slice: 'die Scheibe, das Stück',
  bottle: 'die Flasche',
  bag: 'die Tasche, die Tüte',
  box: 'die Schachtel, der Karton',
  chair: 'der Stuhl',
  seat: 'der Sitzplatz',
  child: 'das Kind',
  children: 'die Kinder',
  people: 'die Leute, die Menschen',
  visitor: 'der Besucher',
  school: 'die Schule',
  page: 'die Seite (im Buch)',
  block: 'der Block, der Klotz',
  fence: 'der Zaun',
  garden: 'der Garten',
  shop: 'der Laden',
  price: 'der Preis',
  cost: 'kosten, die Kosten',
  money: 'das Geld',
  ticket: 'die Eintrittskarte',
  train: 'der Zug',
  journey: 'die Reise, die Fahrt',
  crossing: 'die Überfahrt, der Übergang',
  sticker: 'der Aufkleber',
  marble: 'die Murmel',
  sweet: 'das Bonbon; süß',
};

// Word normalisation. Only ever runs on a MISS, so an over-eager rule can
// never override a real entry ('other' hits directly; it is never stripped to
// 'oth'). Order matters: the more specific ending is tried first.
const RULES = [
  (w) => (w.endsWith('ies') ? w.slice(0, -3) + 'y' : null),   // carries → carry
  (w) => (w.endsWith('ied') ? w.slice(0, -3) + 'y' : null),   // multiplied → multiply
  (w) => (w.endsWith('es') ? w.slice(0, -2) : null),          // boxes → box
  (w) => (w.endsWith('s') ? w.slice(0, -1) : null),           // angles → angle
  (w) => (w.endsWith('ing') ? w.slice(0, -3) : null),         // rounding → round
  (w) => (w.endsWith('ing') ? w.slice(0, -3) + 'e' : null),   // sharing → share
  (w) => (w.endsWith('ed') ? w.slice(0, -2) : null),          // needed → need
  (w) => (w.endsWith('d') ? w.slice(0, -1) : null),           // used → use
  (w) => (w.endsWith('est') ? w.slice(0, -3) : null),         // longest → long
  (w) => (w.endsWith('er') ? w.slice(0, -2) : null),          // smaller → small
  // bigger → bigg → big: undo the doubled consonant left by the two rules above
  (w) => (/([bdfglmnprt])\1$/.test(w) ? w.slice(0, -1) : null),
];

// Strip the punctuation a word carries in running text. Kept separate from the
// tokenizer so a word coming from anywhere else normalises the same way.
export function normaliseWord(raw) {
  return String(raw ?? '')
    .toLowerCase()
    .replace(/[’']s$/, '')            // possessive: "Ava's" → "ava"
    .replace(/^[^a-z]+|[^a-z-]+$/g, '');
}

// The German gloss for one English word, or null if this list does not know it
// (the caller then asks the tutor). Tries the word itself first, then one
// morphological step, then two — 'bigger' needs -er and the doubled consonant.
export function lookupGloss(raw) {
  const word = normaliseWord(raw);
  if (!word) return null;
  if (GLOSSARY[word]) return GLOSSARY[word];
  const seen = new Set([word]);
  let frontier = [word];
  for (let depth = 0; depth < 2; depth++) {
    const next = [];
    for (const w of frontier) {
      for (const rule of RULES) {
        const cand = rule(w);
        if (!cand || cand.length < 2 || seen.has(cand)) continue;
        if (GLOSSARY[cand]) return GLOSSARY[cand];
        seen.add(cand);
        next.push(cand);
      }
    }
    frontier = next;
  }
  return null;
}
