import { mount, go, store, cur, onAfterRender, rerender, currentScreen } from './shell/core.js';
import { seedY6FromY5 } from './maths/y5-bridge.js';
import { probeServer } from './qa/endpoint.js';
import { BUILD } from './shell/build.js';
import { curricula } from './shell/storage.js';
import './ui/home.js';
import './ui/today.js';
import './ui/map.js';
import './ui/session.js';
import './ui/parent.js';
import { mountBuddy, updateBuddy } from './ui/buddy.js';
// English module (Wordforge port) — self-registering screens, same pattern
// as the maths ui/*.js imports above.
import './english/ui/home.js';
import './english/ui/read.js';
import './english/ui/talk.js';
import './english/ui/create.js';

mount(document.getElementById('root'));

// Focused practice is a same-run bonus: never resume it across reloads, so it
// can never shadow a resumable daily lesson on the next launch.
if (cur().focusSession) { cur().focusSession = null; store.save(); }

// A session generated by an older build is thrown away rather than resumed.
// Its questions were stored FINISHED — prompt and rendered SVG — so a content
// fix cannot reach them; on the device two faulty questions survived the fix,
// the deploy and two restarts because the morning's session was still in the
// store. Losing a half-finished session on deploy day is the cheaper mistake.
// See shell/build.js.
for (const name of curricula(store.state)) {
  const slice = store.state.maths[name];
  if (slice.activeSession && slice.activeSession.build !== BUILD) {
    slice.activeSession = null;
    store.save();
  }
}

// An imported Year 5 backup replaces the Year 6 warm-up check: its scores seed
// the topic priors and the check is marked done (maths/y5-bridge.js). Runs on
// every launch because the device where the import already happened would
// otherwise still be waiting for a check it must never sit — the function is a
// no-op the moment the slice has any evidence of its own.
if (seedY6FromY5(store.state)) store.save();

// Ask the server once whether it holds the API keys, so the AI features can be
// offered on their real availability instead of on whether a key was typed
// into this device (app/js/qa/endpoint.js). Fire-and-forget: everything treats
// an unfinished probe as "available", so nothing waits on it.
probeServer().then(() => {
  // The answer decides whether the buddy and the microphone are offered at
  // all, and it lands a moment after the first paint. Only the launch screen
  // is redrawn: a later screen is mid-interaction and must not be rebuilt
  // under him for a status line.
  if (currentScreen() === 'home') rerender();
  updateBuddy();
});

// Global buddy FAB: mounted once outside #root, refreshed on every navigation.
mountBuddy();
onAfterRender(updateBuddy);

go('home');

// Offline support once served over http(s). Skipped on localhost so local
// development and the test runner always see fresh files.
const isLocal = ['localhost', '127.0.0.1'].includes(location.hostname);
if ('serviceWorker' in navigator && location.protocol.startsWith('http') && !isLocal) {
  navigator.serviceWorker.register('./sw.js').catch(() => {});
}
